# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_world/service.proto

require 'google/protobuf'


descriptor_data = "\n\x19hello_world/service.proto\x12\x07\x65xample\"\x1c\n\x0cHelloRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\" \n\rHelloResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2D\n\nHelloWorld\x12\x36\n\x05Hello\x12\x15.example.HelloRequest\x1a\x16.example.HelloResponseb\x06proto3"

pool = ::Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Example
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.HelloRequest").msgclass
  HelloResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("example.HelloResponse").msgclass
end
